# Generated by Django 3.2.6 on 2021-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_textpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
