# Generated by Django 3.2.6 on 2021-08-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210810_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='textpage',
            name='search_image',
        ),
    ]
